spring:
  data:
    mongodb:
      uri: mongodb+srv://tarun:f1StMmlq25XUsg2e@cluster0.4d90q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: GheeTestDB
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /api
