spring:
  data:
    mongodb:
      uri: mongodb+srv://tarun:f1StMmlq25XUsg2e@cluster0.4d90q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: GheeTestDBcopy
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "whitelegend56@gmail.com"
    password: "${PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8080
  servlet:
    context-path: /api

